# Generated by Django 5.0.6 on 2024-05-18 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cities_set",
                to="core.country",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="locations_set",
                to="core.city",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="locations_set",
                to="core.country",
            ),
        ),
        migrations.AlterField(
            model_name="locationcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations_categories_set",
                to="core.category",
            ),
        ),
        migrations.AlterField(
            model_name="locationcategory",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations_categories_set",
                to="core.location",
            ),
        ),
    ]
